server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 123456
logging:
  level:
    com.book: debug
public:
  url:
    - /administer/noAuth
    - /administer/login
    - /administer/loginToken
    - /doc.html
    - /swagger-resources
    - /swagger-ui.html
    - /webjars/.*
    - /v2/.*
mybatis-plus:
  mapper-locations: classpath:mapper.book/*Mapper.xml
  configuration:
    # 是否开启自动驼峰命名规则映射：从数据库列名到java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
